using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;

namespace TheByteClubPOS
{
    public partial class ManageSales : Form
    {
        public ManageSales()
        {
            InitializeComponent();
        }

        private void LoadMasterSalesData()
        {
            try
            {
                // TODO: This line of code loads data into the 'dsSamsLiqourShop.SalesSummaryInnerJoinDT' table. You can move, or remove it, as needed.
                this.salesSummaryInnerJoinDTTableAdapter.FillWithDetails(this.dsSamsLiqourShop.SalesSummaryInnerJoinDT);
                salesSummaryInnerJoinDTDataGridView.ClearSelection();

                // Clear out label text if no record is active on initial load
                lblTransactionDetails.Text = "Transaction Details (Select a sale above)";
            }
            catch (Exception ex)
            {
                MessageBox.Show("Error loading sales history summary: " + ex.Message, "Database Error", MessageBoxButtons.OK, MessageBoxIcon.Error);
            }
        }

        private void ManageSales_Load(object sender, EventArgs e)
        {
            LoadMasterSalesData();
            
        }

        private void salesSummaryInnerJoinDTDataGridView_SelectionChanged(object sender, EventArgs e)
        {
            // Ensure a row is selected and it isn't an empty spacer row
            if (salesSummaryInnerJoinDTDataGridView.CurrentRow != null && !salesSummaryInnerJoinDTDataGridView.CurrentRow.IsNewRow && salesSummaryInnerJoinDTDataGridView.CurrentRow.Index >= 0)
            {
                try
                {
                    // 3. Extract the row primary key using DataRowView mapping to avoid index mismatch bugs
                    DataRowView currentRow = (DataRowView)salesSummaryInnerJoinDTDataGridView.CurrentRow.DataBoundItem;
                    int selectedSaleID = Convert.ToInt32(currentRow["Sale_ID"]);

                    lblTransactionDetails.Text = $"Transaction Details (Sale ID: {selectedSaleID})";

                    // 4. Pass the selected ID to filter the line items table breakdown automatically
                    this.saleLinesSummaryInnerJoinDTTableAdapter.FillBySaleID(this.dsSamsLiqourShop.SaleLinesSummaryInnerJoinDT, selectedSaleID);
                }
                catch (Exception ex)
                {
                    MessageBox.Show($"Error loading matching transaction details: {ex.Message}", "Data Sync Error", MessageBoxButtons.OK, MessageBoxIcon.Warning);
                }
            }
        }

        private void btnClear_Click(object sender, EventArgs e)
        {
            txtSearch.Text = "";
        }

        private void btnRefresh_Click(object sender, EventArgs e)
        {
            txtSearch.Clear(); // Wipe the search input window to reset display bounds
            LoadMasterSalesData();
        }

        private void txtSearch_TextChanged(object sender, EventArgs e)
        {
            // Ignore filtering if the textbox currently contains the placeholder text
            if (txtSearch.Text == "Search by Customer, Employee or Promo..." && txtSearch.ForeColor == Color.Gray)
            {
                return;
            }

            try
            {
                // This targets the BindingSource generated by your dataset table component
                if (string.IsNullOrWhiteSpace(txtSearch.Text))
                {
                    // If search bar is blank, remove filters entirely
                    salesSummaryInnerJoinDTBindingSource.Filter = "";
                }
                else
                {
                    // Safely escapes characters and filters both Customer and Employee column data simultaneously
                    string safeSearchTerm = txtSearch.Text.Replace("'", "''").Trim();
                    salesSummaryInnerJoinDTBindingSource.Filter = string.Format(
                        "Customer_Details LIKE '%{0}%' OR " +
                        "Employee_Name LIKE '%{0}%' OR " +
                        "Sale_Status LIKE '%{0}%' OR " +
                        "SaleType_Name LIKE '%{0}%' OR " +
                        "Sale_Discount_Name LIKE '%{0}%' OR " +
                        "Convert(Sale_DateTime, 'System.String') LIKE '%{0}%' OR " +
                        "Convert(Sale_TotalAmount, 'System.String') LIKE '%{0}%'",
                        safeSearchTerm
                    );
                }
            }
            catch (Exception ex)
            {
                // Soft warning log to prevent crashing if temporary syntax string clipping occurs during rapid input
                System.Diagnostics.Debug.WriteLine("Search string processing mismatch: " + ex.Message);
            }
        }

        private void txtSearch_Enter(object sender, EventArgs e)
        {
            if (txtSearch.Text == "Search by Customer, Employee or Promo..." && txtSearch.ForeColor == Color.Gray)
            {
                txtSearch.Text = "";
                txtSearch.ForeColor = Color.Black; // Change text back to crisp typing color
            }
        }

        private void txtSearch_Leave(object sender, EventArgs e)
        {
            if (string.IsNullOrWhiteSpace(txtSearch.Text))
            {
                txtSearch.Text = "Search by Customer, Employee or Promo...";
                txtSearch.ForeColor = Color.Gray;
                salesSummaryInnerJoinDTBindingSource.Filter = ""; // Clear active filters
            }
        }
    }
}
